version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tf_app_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tf_db
      - POSTGRES_USER=tf_admin
      - POSTGRES_PASSWORD=tf_2021

  frontend:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: tf_app_frontend
    command: yarn start
    volumes:
      - .:/app
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - web
    stdin_open: true

  storybook:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: tf_app_storybook
    command: yarn storybook
    volumes:
      - .:/app
      - /app/frontend/node_modules
    ports:
      - 6006:6006
    depends_on:
      - web
    stdin_open: true

volumes:
  postgres_data:
