# Generated by Django 3.1 on 2021-02-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210213_1445'),
        ('blog', '0003_auto_20210213_1547'),
    ]

    operations = [
    ]
