# Generated by Django 3.1 on 2021-02-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0002_auto_20210213_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_cta',
            new_name='banner_cta_1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
