# Generated by Django 3.1 on 2021-02-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210213_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_cta_1',
            new_name='button_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_cta_2',
            new_name='button_2',
        ),
    ]
