# Generated by Django 3.1 on 2021-02-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_welcomecarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeCarousel',
        ),
    ]
