# Generated by Django 3.1 on 2021-02-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_welcomecarousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='button_1',
            new_name='button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='button_2',
        ),
    ]
