# Generated by Django 3.1 on 2021-02-13 23:02

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210213_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.StreamBlock([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', blog.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('image_carousel', wagtail.core.blocks.ListBlock(blog.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(blog.blocks.CustomImageChooserBlock()))]))], blank=True, null=True),
        ),
    ]
