# Generated by Django 3.1 on 2021-02-23 12:43

from django.db import migrations
import stream.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210219_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='button',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.StreamBlock([('headings', wagtail.core.blocks.StreamBlock([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('h3', wagtail.core.blocks.CharBlock()), ('h4', wagtail.core.blocks.CharBlock()), ('h5', wagtail.core.blocks.CharBlock()), ('h6', wagtail.core.blocks.CharBlock())])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('column', wagtail.core.blocks.StreamBlock([('two_columns', wagtail.core.blocks.StreamBlock([('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', stream.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('two_text', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock())]))])), ('three_columns', wagtail.core.blocks.StreamBlock([('three', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock()), ('text_3', wagtail.core.blocks.RichTextBlock())]))])), ('four_columns', wagtail.core.blocks.StreamBlock([('four_text', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock()), ('text_3', wagtail.core.blocks.RichTextBlock()), ('text_4', wagtail.core.blocks.RichTextBlock())]))]))])), ('slider', wagtail.core.blocks.StreamBlock([('image_slider', wagtail.core.blocks.ListBlock(stream.blocks.CustomImageChooserBlock())), ('animated_slider', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.RichTextBlock()), ('button_text', wagtail.core.blocks.CharBlock(required=False)), ('button', wagtail.core.blocks.PageChooserBlock(required=False)), ('image', stream.blocks.CustomImageChooserBlock(required=True))])))])), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(stream.blocks.CustomImageChooserBlock())), ('two_columns', wagtail.core.blocks.StreamBlock([('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', stream.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('two_text', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock())]))])), ('three_columns', wagtail.core.blocks.StreamBlock([('three', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock()), ('text_3', wagtail.core.blocks.RichTextBlock())]))])), ('four_columns', wagtail.core.blocks.StreamBlock([('four_text', wagtail.core.blocks.StructBlock([('text_1', wagtail.core.blocks.RichTextBlock()), ('text_2', wagtail.core.blocks.RichTextBlock()), ('text_3', wagtail.core.blocks.RichTextBlock()), ('text_4', wagtail.core.blocks.RichTextBlock())]))]))]))], blank=True, null=True),
        ),
    ]
